use std::process::exit;

pub fn failure() -> ! {
    exit(1)
}
